version: '3.4'

services:
  flexi-schedule-api:
    image: flexischeduleapi:dev
    container_name: flexi-schedule-api
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - sqlserver
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_NAME: FlexiSchedule
      DB_USER: sa
      DB_PASSWORD: ${SA_PASSWORD}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
    sqlserver-data: