version: '3.4'

services:
  flexi-schedule-api:
    build:
      context: .
      dockerfile: FlexiSchedule.Api/Dockerfile
    volumes:
      - .:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1