global using FlexiSchedule.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using FlexiSchedule.Infrastructure.Persistence;
global using Microsoft.Extensions.DependencyInjection;
global using FlexiSchedule.Domain.Interfaces;
global using FlexiSchedule.Infrastructure.Persistence.Repositories;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.ComponentModel.DataAnnotations.Schema;